<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
<path d="M3 13.5l6-6" fill="none" stroke="#B58B66" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<g transform="rotate(45 10.25 5.25)"><rect x="6" y="3.25" width="8.5" height="4" rx="1" fill="#EF6C4B"/></g>
</svg>
