//! 构建期信息：把应用信息表填上版本号后嵌进可执行文件，让未打包成 .app 时也有应用元数据，
//! 打包 .app 时也直接用这份表；再把内置的配色主题和命令补全用的命令规格编进二进制。

use std::{env, fs, path::PathBuf, process::Command};

fn main() {
    // 当前提交变化时重新生成构建号。
    println!("cargo:rerun-if-changed=../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../.git/refs/heads");
    let version = env::var("CARGO_PKG_VERSION").unwrap();
    let commit = git_short_head().unwrap_or_else(|| "unknown".into());
    // 关于面板显示为「版本 0.1.0 (0.1.0.<commit>)」。
    let build = format!("{version}.{commit}");

    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        // 模板里的 @VERSION@、@BUILD@ 换成实际版本号与构建号。
        println!("cargo:rerun-if-changed=Info.plist");
        let template = fs::read_to_string("Info.plist").unwrap();
        let plist = PathBuf::from(env::var("OUT_DIR").unwrap()).join("Info.plist");
        fs::write(&plist, template.replace("@VERSION@", &version).replace("@BUILD@", &build)).unwrap();
        // 裸可执行文件的 NSBundle.mainBundle 会读 __TEXT,__info_plist 段，
        // 系统关于面板因此能拿到名称、版本、版权，并按 CFBundleAllowMixedLocalizations
        // 跟随系统语言显示「版本」等字样。
        println!(
            "cargo:rustc-link-arg-bins=-Wl,-sectcreate,__TEXT,__info_plist,{}",
            plist.display()
        );
    }

    bundle_themes();
    bundle_command_specs();
}

/// 把手写的命令规格（command-signatures 子模块 json 目录顶层的文件）逐个压紧、压缩，接成
/// 一整块 `command_specs.bin`，再生成按命令名排序的 `(名字, 偏移, 长度, 说明)` 表
/// `command_specs.rs`；说明是命令本身的一句话描述，补命令名时不用解压整个规格。一个文件有
/// 几个名字就占几项，指向同一段数据。自动生成的规格
/// （autogenerated、overrides 子目录）是 PowerShell 用的，不要。
fn bundle_command_specs() {
    let dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .join("../../vendor/command-signatures/command-signatures/json");
    println!("cargo:rerun-if-changed={}", dir.display());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("{}: {err}; run `make submodules` first", dir.display()))
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    files.sort();

    let mut blob = Vec::new();
    let mut index: Vec<(String, usize, usize, String)> = Vec::new();
    for path in &files {
        let json: serde_json::Value = serde_json::from_slice(&fs::read(path).unwrap())
            .unwrap_or_else(|err| panic!("{}: {err}", path.display()));
        let names: Vec<String> = match &json["name"] {
            serde_json::Value::String(name) => vec![name.clone()],
            serde_json::Value::Array(names) => names.iter().filter_map(|n| n.as_str().map(str::to_owned)).collect(),
            _ => panic!("{}: no command name", path.display()),
        };
        let description = json["description"].as_str().unwrap_or_default().to_owned();
        // 去掉缩进和换行再压缩，嵌进去的数据小两成多。
        let compact = serde_json::to_vec(&json).unwrap();
        let compressed = miniz_oxide::deflate::compress_to_vec(&compact, 9);
        let offset = blob.len();
        blob.extend_from_slice(&compressed);
        for name in names {
            index.push((name, offset, compressed.len(), description.clone()));
        }
    }
    index.sort();
    index.dedup_by(|a, b| a.0 == b.0);

    fs::write(out_dir.join("command_specs.bin"), &blob).unwrap();
    let mut out = String::from("&[\n");
    for (name, offset, len, description) in &index {
        out += &format!("    ({name:?}, {offset}, {len}, {description:?}),\n");
    }
    out += "]\n";
    fs::write(out_dir.join("command_specs.rs"), out).unwrap();
}

/// 生成按名字排序的 `(名字, 内容)` 表，供 `BUNDLED_THEMES` 使用。
fn bundle_themes() {
    let dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap()).join("themes");
    // 指向目录时，目录里任何文件变动都会触发重新生成。
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = fs::read_dir(&dir)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().into_string().unwrap())
        // 隐藏文件（如 Finder 生成的 .DS_Store）不是主题，二进制内容也进不了 include_str!。
        .filter(|name| name != "LICENSE" && !name.starts_with('.'))
        .collect();
    names.sort();

    let mut out = String::from("&[\n");
    for name in &names {
        out += &format!("    ({name:?}, include_str!({:?})),\n", dir.join(name));
    }
    out += "]\n";
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("themes.rs"), out).unwrap();
}

fn git_short_head() -> Option<String> {
    let out = Command::new("git")
        .args(["rev-parse", "--short=7", "HEAD"])
        .output()
        .ok()
        .filter(|out| out.status.success())?;
    Some(String::from_utf8_lossy(&out.stdout).trim().to_owned())
}
