//! 构建期把命令补全用的命令规格压缩后编进二进制。

use std::{env, fs, path::PathBuf};

fn main() {
    bundle_command_specs();
}

/// 把手写的命令规格（command-signatures 子模块 json 目录顶层的文件）逐个压紧、压缩，接成
/// 一整块 `command_specs.bin`，再生成按命令名排序的 `(名字, 偏移, 长度, 说明)` 表
/// `command_specs.rs`；说明是命令本身的一句话描述，补命令名时不用解压整个规格。一个文件有
/// 几个名字就占几项，指向同一段数据。自动生成的规格
/// （autogenerated、overrides 子目录）是 PowerShell 用的，不要。
fn bundle_command_specs() {
    let dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap())
        .join("../../vendor/command-signatures/command-signatures/json");
    println!("cargo:rerun-if-changed={}", dir.display());
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    let mut files: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|err| panic!("{}: {err}; run `make submodules` first", dir.display()))
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    files.sort();

    let mut blob = Vec::new();
    let mut index: Vec<(String, usize, usize, String)> = Vec::new();
    for path in &files {
        let json: serde_json::Value = serde_json::from_slice(&fs::read(path).unwrap())
            .unwrap_or_else(|err| panic!("{}: {err}", path.display()));
        let names: Vec<String> = match &json["name"] {
            serde_json::Value::String(name) => vec![name.clone()],
            serde_json::Value::Array(names) => names.iter().filter_map(|n| n.as_str().map(str::to_owned)).collect(),
            _ => panic!("{}: no command name", path.display()),
        };
        let description = json["description"].as_str().unwrap_or_default().to_owned();
        // 去掉缩进和换行再压缩，嵌进去的数据小两成多。
        let compact = serde_json::to_vec(&json).unwrap();
        let compressed = miniz_oxide::deflate::compress_to_vec(&compact, 9);
        let offset = blob.len();
        blob.extend_from_slice(&compressed);
        for name in names {
            index.push((name, offset, compressed.len(), description.clone()));
        }
    }
    index.sort();
    index.dedup_by(|a, b| a.0 == b.0);

    fs::write(out_dir.join("command_specs.bin"), &blob).unwrap();
    let mut out = String::from("&[\n");
    for (name, offset, len, description) in &index {
        out += &format!("    ({name:?}, {offset}, {len}, {description:?}),\n");
    }
    out += "]\n";
    fs::write(out_dir.join("command_specs.rs"), out).unwrap();
}
